maintenance_system/accounts/urls.py
from django.urls import include, path
from accounts.views import manage_accounts, signup, signin, forgot_password, signup_success, change_password, logout_view
from django.contrib.auth import views as auth_views
from maintenance_system import settings

urlpatterns = [
    path('manage/', manage_accounts, name='manage_account'),
    path('signup/', signup, name='signup'),
    path('signup_success/', signup_success, name='signup_success'),
    path('signin/', signin, name='signin'),
    path('forgot_password/', forgot_password, name='forgot_password'),
    path('change_password/', change_password, name='change_password'),
    path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
]

maintenance_system/maintenance_system/urls.py
from django.contrib import admin
from django.urls import include, path
from accounts.views import dashboard, activate_user
from shift_schedule.views import shift_schedule, get_shift_schedule_item, delete_shift_schedule, shift_csv_template
from job_schedule.views import job_schedule, send_feedback_email, show_image, job_schedule_detail, task_schedule_detail, delete_job_schedule, fault_form, fault_success, feedback_form, feedback_success
from maintenance_system.api import api as maintenance_system_api
urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('user/', include("accounts.urls")),
    path('shifts/', shift_schedule, name="shift_schedule"),
    path("shift_template/", shift_csv_template, name="shift_template"),
    path('jobs/', job_schedule, name="job_schedule"),
    path('shift_detail/', get_shift_schedule_item, name="shift_detail"),
    path('job_detail/', job_schedule_detail, name="job_detail"),
    path('task_detail/', task_schedule_detail, name="task_detail"),
    # forms
    path('fault_form/', fault_form, name="fault_form"),
    path('fault_success/', fault_success, name="fault_success"),
    path('feedback_success/', feedback_success, name="feedback_success"),
    path('shift_delete/<uuid:shift_id>/', delete_shift_schedule, name="delete_shift"),
    path('job_delete/<uuid:job_id>/', delete_job_schedule, name="delete_job"),
    path('send_feedback_email/<uuid:job_id>/', send_feedback_email, name="send_feedback_email"),
    path('feedback/', feedback_form, name="feedback_form"),
    path('activate_account/<int:user_id>/', activate_user, name="activate_account"),
    path('show_image/<uuid:task_id>/', show_image, name='show_image'),
    path('dashboard/', dashboard, name='dashboard'),
    path("api/", maintenance_system_api.urls),
]

maintenance_system/shift_schedule/models.py
from django.db import models
from accounts.models import User
import uuid

class ShiftSchedule(models.Model):
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique = True)
  shift_date = models.DateField(blank=True, null=True)
  assigned_staff_name = models.CharField(max_length=254,default='')
  shift_type = models.CharField(max_length=254, choices=(
      ('Morning', 'Morning'),
      ('Afternoon', 'Afternoon'),
      ('Evening', 'Evening'),
  ), null=True, blank=True)
  shift_day = models.CharField(max_length=254, choices=(
      ('Mon', 'Monday'),
      ('Tue', 'Tuesday'),
      ('Wed', 'Wednesday'),
      ('Thu', 'Thursday'),
      ('Fri', 'Friday'),
      ('Sat', 'Saturday'),
      ('Sun', 'Sunday'),
  ),null=True, blank=True)
  shift_dept = models.CharField(max_length=254, null=True, blank=True)
  # Not used
#   start_time = models.TimeField(null=True, blank=True)
#   end_time = models.TimeField(null=True, blank=True)
  

maintenance_system/shift_schedule/forms.py
from django import forms
from .models import ShiftSchedule
from accounts.models import User
from django.shortcuts import render, get_object_or_404


class ShiftScheduleForm(forms.ModelForm):
    # assigned_staff_id = forms.ChoiceField(choices=[], label='Technician')
    # assigned_staff_id = forms.ModelChoiceField(queryset=User.objects.filter(is_active=True, is_superuser=False), label='Technician')
    action_type = forms.CharField(widget=forms.HiddenInput(), initial='add_schedule')
    shift_date = forms.DateField(required=True)
    
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    # @staticmethod
    # def label_from_instance(obj):
    #     return "%s" % obj.name
    
    class Meta:
        model = ShiftSchedule
        fields = ['shift_date', 'assigned_staff_name', 'shift_type']
        
    # def clean(self):
    #     cleaned_data = super().clean()
    #     start_time = cleaned_data.get('start_time')
    #     end_time = cleaned_data.get('end_time')

    #     # Validate start time and end time
    #     if start_time and end_time and start_time >= end_time:
    #         raise forms.ValidationError("End time must be after start time.")

    #     return cleaned_data


class UpdateShiftScheduleForm(forms.ModelForm):
    # assigned_staff_id = forms.ChoiceField(choices=[], label='Technician')
    # assigned_staff_id = forms.ModelChoiceField(queryset=User.objects.filter(is_active=True, is_superuser=False), label='Technician')
    action_type = forms.CharField(widget=forms.HiddenInput(), initial='update_schedule')
    update_shift_id = forms.CharField(widget=forms.HiddenInput())
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['shift_date'].widget.attrs.update({'id': 'id_edit_shift_date'})
        self.fields['assigned_staff_name'].widget.attrs.update({'id': 'id_edit_assigned_staff_name'})
        self.fields['shift_type'].widget.attrs.update({'id': 'id_edit_shift_type'})
        self.fields['update_shift_id'].widget.attrs.update({'id': 'id_shift_id', 'name': 'shift_id'})
        
        # self.fields['assigned_staff_id'].label_from_instance = self.label_from_instance
    
    # @staticmethod
    # def label_from_instance(obj):
    #     return "%s" % obj.name
    
    class Meta:
        model = ShiftSchedule
        fields = ['shift_date', 'assigned_staff_name', 'shift_type']
        
    # def clean(self):
    #     cleaned_data = super().clean()
    #     start_time = cleaned_data.get('start_time')
    #     end_time = cleaned_data.get('end_time')

    #     # Validate start time and end time
    #     if start_time and end_time and start_time >= end_time:
    #         raise forms.ValidationError("End time must be after start time.")

    #     return cleaned_data
    
    def save(self, commit=True):
        instance = super().save(commit=False)
        if commit:
            instance.save()
        return instance


class GenShiftScheduleForm(forms.Form):
    # assigned_staff_id = forms.ChoiceField(choices=[], label='Technician')
    action_type = forms.CharField(widget=forms.HiddenInput(), initial='gen_schedule')
    start_date = forms.DateField(required=True)
    end_date = forms.DateField(required=True)
    
        
    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get('start_date')
        end_date = cleaned_data.get('end_date')

        # Validate start time and end time
        if start_date and end_date and start_date >= end_date:
            raise forms.ValidationError("End date must be after start date.")

        return cleaned_data



class UploadCSVForm(forms.Form):
    action_type = forms.CharField(widget=forms.HiddenInput(), initial='upload_schedule')
    csv_file = forms.FileField()

maintenance_system/shift_schedule/views.py
from django.shortcuts import render, redirect, get_object_or_404
from accounts.models import User, Staff
from  .forms import ShiftScheduleForm, UpdateShiftScheduleForm, GenShiftScheduleForm, UploadCSVForm
from django.contrib import messages
from .models import ShiftSchedule
from django.http import JsonResponse
import os
from django.http import HttpResponse
from django.conf import settings
from django.db import transaction
import csv
from datetime import datetime, timedelta
import pandas as pd
import io
import magic
from django.contrib.auth.decorators import login_required



# Create your views here.
@login_required
def shift_schedule(request):
    user = request.user
    if request.method == 'POST':
        if request.POST.get('action_type') == 'add_schedule':
            return add_shift_schedule(request)
        elif request.POST.get('action_type') == 'update_schedule':
            return edit_shift_schedule(request)
        elif request.POST.get('action_type') == 'gen_schedule':
            return shift_csv_template(request)
        elif request.POST.get('action_type') == 'upload_schedule':
            return upload_shift(request)
        else:
            return redirect(request.path)
        form = ShiftScheduleForm(request.POST)
    else:
        users_dept = get_object_or_404(Staff, user=user).department
        if users_dept == 'Admin':
            shifts = ShiftSchedule.objects.all()
        else:
            shifts = ShiftSchedule.objects.filter(shift_dept=users_dept)
        form = ShiftScheduleForm()
        editform = UpdateShiftScheduleForm()
        genform = GenShiftScheduleForm()
        uploadform = UploadCSVForm()
        context = {
            'form': form,
            'genform': genform,
            'editform': editform,
            'uploadform': uploadform,
            'shifts': shifts,
            'user': user
        }
        return render(request,'shift_schedule.html', context)


# Generate shift template
@login_required
def shift_csv_template(request):
    genform = GenShiftScheduleForm(request.POST)
    if genform.is_valid():
        start_date = genform.cleaned_data['start_date']
        end_date = genform.cleaned_data['end_date']
        date_length = len(pd.date_range(start_date, end_date))
        
        
        user = request.user
        
        users_dept = get_object_or_404(Staff, user=user).department
        departments = Staff.objects.filter(department=users_dept)
        # get all staff memebers in signed in users department
        user_names = [user.user.name for user in departments]
        
        shift_days = ['Morning', 'Afternoon', 'Evening']
        
        repetitions = 3
        date_length_repitiion = len(pd.date_range(start_date, end_date).repeat(repetitions))



        df1 = pd.DataFrame({
                'id': range(1, len(user_names)+1),
                'Staff name': user_names,
            })
            

        df2 = pd.DataFrame({
                'id': range(1, date_length_repitiion+1),
                'Date': pd.date_range(start_date, end_date).repeat(repetitions),
            })

        df3 = pd.DataFrame({
                'id': range(1, len(shift_days * date_length)+1),
                'Shift type': shift_days * date_length,
            })
        temp_df = pd.merge(df1, df2, on='id', how='outer')

        shift_df = pd.merge(temp_df, df3, on='id', how='outer')

        shift_df_mod = shift_df.drop('id',axis=1)
        
        # Create the CSV content in memory
        csv_content = shift_df_mod.to_csv(index=False)

        # Serve the CSV as a download response
        response = HttpResponse(csv_content, content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="shifts_template.csv"'
    else:
        messages.error(request, 'Invalid date range')
        return redirect(request.path)    
    
    return response


# Upload shift template
@login_required
def upload_shift(request):
    uploadform = UploadCSVForm(request.POST, request.FILES)
    if uploadform.is_valid():
        csv_file = request.FILES['csv_file']
        user = request.user 
        users_dept = get_object_or_404(Staff, user=user).department
        
        mime = magic.Magic(mime=True)
        file_mime_type = mime.from_buffer(csv_file.read(1024))
        csv_file.seek(0) 
        
        # Validate the file type is csv
        valid_mime_types = ['text/csv', 'application/csv', 'text/plain', 'application/vnd.ms-excel']
        if file_mime_type not in valid_mime_types or not csv_file.name.endswith('.csv'):
            messages.error(request, 'File is not CSV type')
            return redirect(request.path)
        

        # Use pandas to read the CSV file
        try:
            data_set = pd.read_csv(csv_file).fillna('')
        except pd.errors.ParserError:
            messages.error(request, 'Error reading CSV file. Please check the file format.')
            return redirect(request.path)

        # Check if all required columns are present
        required_columns = ['Staff name', 'Date', 'Shift type']
        if not all(column in data_set.columns for column in required_columns):
            messages.error(request, 'CSV file is missing required columns.')
            return redirect(request.path)
        
        
        num_shifts_added = 0
        with transaction.atomic():
            # Iterate through the DataFrame rows
            for index, row in data_set.iterrows():
                staff_name = row.get('Staff name', '').strip()
                shift_date = row.get('Date', '').strip()
                shift_type = row.get('Shift type', '').strip()

                if not staff_name or not shift_type:
                    continue  # Skip rows where both 'Staff name' and 'Shift type' are empty

                try:
                    shift_date = datetime.strptime(shift_date, '%Y-%m-%d').date()
                except ValueError:
                    messages.error(request, f'Invalid date format in row {index+2}.')
                    return redirect(request.path)

                shift_day = shift_date.strftime('%a')  # Get the abbreviated day of the week (Mon, Tue, etc.)

                ShiftSchedule.objects.create(
                    assigned_staff_name=staff_name,
                    shift_date=shift_date,
                    shift_day=shift_day,
                    shift_dept=users_dept,
                    shift_type=shift_type
                )
                num_shifts_added += 1
            
            messages.success(request, f'Successfully added {num_shifts_added} shifts.')
            return redirect(request.path)

@login_required
def add_shift_schedule(request):
    form = ShiftScheduleForm(request.POST)
    if form.is_valid():
        shift_schedule = form.save(commit=False)
        
        user = request.user 
        users_dept = get_object_or_404(Staff, user=user).department
        # Calculate the shift day from the shift date
        shift_date = form.cleaned_data.get('shift_date')
        if shift_date:
            shift_day = shift_date.strftime('%a')  # Get the abbreviated day of the week (Mon, Tue, etc.)
            shift_schedule.shift_day = shift_day
        shift_schedule.shift_dept = users_dept
        
        shift_schedule.save()
            
        messages.success(request, 'Shift added successfully.')
        return redirect('shift_schedule')  # Redirect to desired location
    else:
        for error in form.errors:
            messages.error(request, form.errors[error])
    return redirect(request.path)  # Fallback in case of non-POST requests

@login_required
def edit_shift_schedule(request):
    editform = UpdateShiftScheduleForm(request.POST)
    if editform.is_valid():
        # Get shift details
        shift_id = editform.cleaned_data['update_shift_id']
        shift_date = editform.cleaned_data['shift_date']
        shift_assigned_staff_name = editform.cleaned_data['assigned_staff_name']
        shift_type = editform.cleaned_data['shift_type']
        
        try:
            shift = get_object_or_404(ShiftSchedule, pk=shift_id)
        except ShiftSchedule.DoesNotExist:
            messages.error(request, 'Shift not found.')
            return redirect('shift_schedule')
        shift_day = shift_date.strftime('%a')
        
        # Save shift
        shift.shift_date = shift_date
        shift.assigned_staff_name = shift_assigned_staff_name 
        shift.shift_type = shift_type
        shift.shift_day = shift_day
        shift.save()
        
        messages.success(request, 'Shift update successfully.')
        return redirect('shift_schedule')
    else:
        for error in editform.errors:
            messages.error(request, editform.errors[error])
    return redirect(request.path)

@login_required
def delete_shift_schedule(request, shift_id):
    if request.method == 'POST':
        try:
            shift = get_object_or_404(ShiftSchedule, pk=shift_id)
            shift.delete()
            messages.success(request, 'Shift deleted successfully.')
            return redirect('shift_schedule')  # Redirect to desired location
        except ShiftSchedule.DoesNotExist:
            messages.error(request, 'Shift not found.')
            return redirect('shift_schedule')  # Or another error page
    else:
        return redirect('shift_schedule')

@login_required
def get_shift_schedule_item(request):
    shift_schedule_id = request.GET.get('shift_schedule_id')
    shift_schedule = get_object_or_404(ShiftSchedule, pk=shift_schedule_id)
    shift_schedule_data = {
        'shift_schedule_id': shift_schedule.pk,
        'shift_date': shift_schedule.shift_date,
        'assigned_staff_name': shift_schedule.assigned_staff_name,
        'shift_type': shift_schedule.shift_type,
    }
    return JsonResponse(shift_schedule_data)

maintenance_system/shift_schedule/templates/add_shift.html
<div id="hs-modal-add-schedule" class="hs-overlay hs-overlay-open:opacity-100 hs-overlay-open:duration-500 hidden size-full fixed top-0 start-0 z-[80] opacity-0 overflow-x-hidden transition-all overflow-y-auto pointer-events-none">
    <div class="hs-overlay-open:mt-7 hs-overlay-open:opacity-100 hs-overlay-open:duration-500 mt-0 opacity-0 ease-out transition-all sm:max-w-lg sm:w-full m-3 sm:mx-auto">
      <div class="relative flex flex-col bg-white pointer-events-auto shadow-lg rounded-xl dark:bg-gray-800">
        <div class="absolute top-2 end-2">
          <button type="button" class="flex justify-center items-center size-7 text-sm font-semibold rounded-lg border border-transparent text-gray-800 hover:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none dark:text-white dark:border-transparent dark:hover:bg-gray-700" data-hs-overlay="#hs-modal-add-schedule">
            <span class="sr-only">Close</span>
            <svg class="flex-shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
          </button>
        </div>
  <form method="post">
    {% csrf_token %}
    <div class="p-4 sm:p-10 text-center overflow-y-auto">
      {% load widget_tweaks %}
    <!-- Floating Select -->
<div class="relative">
{% render_field form.assigned_staff_name class="peer p-4 pe-9 block w-full border-gray-200 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:ring-gray-600 focus:pt-6 focus:pb-2 [&:not(:placeholder-shown)]:pt-6 [&:not(:placeholder-shown)]:pb-2 autofill:pt-6 autofill:pb-2" %}
<!-- <select id="id-select-technician" class="peer p-4 pe-9 block w-full border-gray-200 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:ring-gray-600
focus:pt-6
focus:pb-2
[&:not(:placeholder-shown)]:pt-6
[&:not(:placeholder-shown)]:pb-2
autofill:pt-6
autofill:pb-2">
  <option selected="">Select technician</option>
  {% for technician in technician_names %}
  <option>{{ technician }}</option>
  {% endfor %}  
</select> -->
<label class="absolute top-0 start-0 p-4 h-full truncate pointer-events-none transition ease-in-out duration-100 border border-transparent dark:text-white peer-disabled:opacity-50 peer-disabled:pointer-events-none
  peer-focus:text-xs
  peer-focus:-translate-y-1.5
  peer-focus:text-gray-500
  peer-[:not(:placeholder-shown)]:text-xs
  peer-[:not(:placeholder-shown)]:-translate-y-1.5
  peer-[:not(:placeholder-shown)]:text-gray-500">Technician</label>
</div>
<!-- End Floating Select -->

<!-- Floating Select -->
<div class="relative mt-4">
{% render_field form.shift_date class="peer p-4 pe-9 block w-full border-gray-200 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:ring-gray-600 focus:pt-6 focus:pb-2 [&:not(:placeholder-shown)]:pt-6 [&:not(:placeholder-shown)]:pb-2 autofill:pt-6 autofill:pb-2" %}
<!-- <select id="id-select-day" class="peer p-4 pe-9 block w-full border-gray-200 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:ring-gray-600
focus:pt-6
focus:pb-2
[&:not(:placeholder-shown)]:pt-6
[&:not(:placeholder-shown)]:pb-2
autofill:pt-6
autofill:pb-2">
  <option selected="">Select day</option>
  <option>Monday</option>
  <option>Tuesday</option>
  <option>Wednesday</option>
  <option>Thursday</option>
  <option>Friday</option>
  <option>Saturday</option>
  <option>Sunday</option>
</select> -->
<label class="absolute top-0 start-0 p-4 h-full truncate pointer-events-none transition ease-in-out duration-100 border border-transparent dark:text-white peer-disabled:opacity-50 peer-disabled:pointer-events-none
  peer-focus:text-xs
  peer-focus:-translate-y-1.5
  peer-focus:text-gray-500
  peer-[:not(:placeholder-shown)]:text-xs
  peer-[:not(:placeholder-shown)]:-translate-y-1.5
  peer-[:not(:placeholder-shown)]:text-gray-500">Date</label>
</div>
<!-- End Floating Select -->
{% render_field form.action_type type="text" class="hidden peer p-4 pe-9 w-full border-gray-200 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:ring-gray-600 focus:pt-6 focus:pb-2 [&:not(:placeholder-shown)]:pt-6 [&:not(:placeholder-shown)]:pb-2 autofill:pt-6 autofill:pb-2" %}


<div class="relative mt-4">
{% render_field form.shift_type type="text" class="peer p-4 pe-9 block w-full border-gray-200 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:ring-gray-600 focus:pt-6 focus:pb-2 [&:not(:placeholder-shown)]:pt-6 [&:not(:placeholder-shown)]:pb-2 autofill:pt-6 autofill:pb-2" %}
<!-- <input type="text" id="start-time" class="peer p-4 pe-9 block w-full border-gray-200 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:ring-gray-600 focus:pt-6 focus:pb-2 [&:not(:placeholder-shown)]:pt-6 [&:not(:placeholder-shown)]:pb-2 autofill:pt-6 autofill:pb-2"> -->
<label for="shift-type" class="absolute top-0 start-0 p-4 h-full truncate pointer-events-none transition ease-in-out duration-100 border border-transparent dark:text-white peer-disabled:opacity-50 peer-disabled:pointer-events-none peer-focus:text-xs peer-focus:-translate-y-1.5 peer-focus:text-gray-500 peer-[:not(:placeholder-shown)]:text-xs peer-[:not(:placeholder-shown)]:-translate-y-1.5 peer-[:not(:placeholder-shown)]:text-gray-500">Shift type</label>
</div>
<!-- End Floating Select -->


<!-- End Floating Select -->
<div class="mt-6 flex justify-center gap-x-4">
<button type="submit" name="action" value="add_shift" class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none" data-hs-overlay="#hs-sign-out-alert">
  Submit
</button>
</div>
      </div>
  </form>
        
        </div>
      </div>
    </div>
  </div>

maintenance_system/shift_schedule/templates/shift_base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required Meta Tags Always Come First -->
  <meta charset="utf-8">
  <meta name="robots" content="max-snippet:-1, max-image-preview:large, max-video-preview:-1">
  <link rel="canonical" href="https://preline.co/">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="This is a simple application layout with header only example using Tailwind CSS.">

  <meta name="twitter:site" content="@preline">
  <meta name="twitter:creator" content="@htmlstream">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title"
    content="Application Layout Navbar: Header using Tailwind CSS | Preline UI, crafted with Tailwind CSS">
  <meta name="twitter:description"
    content="This is a simple application layout with header only example using Tailwind CSS.">
  <meta name="twitter:image" content="../../assets/img/og-image.png">

  <meta property="og:url" content="https://preline.co/">
  <meta property="og:locale" content="en_US">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="Preline">
  <meta property="og:title"
    content="Application Layout Navbar: Header using Tailwind CSS | Preline UI, crafted with Tailwind CSS">
  <meta property="og:description"
    content="This is a simple application layout with header only example using Tailwind CSS.">
  <meta property="og:image" content="../../assets/img/og-image.png">

  <!-- Title -->
  <title>PAU maintenance | shift schedule</title>

  <!-- Favicon -->
  <link rel="shortcut icon" href="../../favicon.ico">

  <!-- Font -->
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <!-- Include Flatpickr CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

  <!-- Include Flatpickr JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
  {% load static %}
  <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
  <!-- Link your Tailwind CSS file -->
  {% tailwind_css %}
</head>

<body class="w-auto h-auto bg-slate-200 dark:bg-slate-900">
  <script src="{% static 'js/hs.theme-appearance.js' %}"></script>
{% include 'partials/navbar.html' %}




{% block shiftcontent %}
{% endblock shiftcontent %}
  
<script>
     flatpickr("#id_start_date", {
        altInput: true,
        altFormat: "F j, Y",
        dateFormat: "Y-m-d",
    });

    flatpickr("#id_end_date", {
        altInput: true,
        altFormat: "F j, Y",
        dateFormat: "Y-m-d",
    });

    flatpickr("#id_shift_date", {
        altInput: true,
        altFormat: "F j, Y",
        dateFormat: "Y-m-d",
    });

    flatpickr("#id_edit_shift_date", {
        // altInput: true,
        altFormat: "F j, Y",
        dateFormat: "Y-m-d",
    });

    // flatpickr("#id_edit_end_time", {
    //     enableTime: true,
    //     noCalendar: true,
    //     dateFormat: "H:i",
    // });

    function get_shift_schedule_detail(shift_id){
  // Get the lead ID from somewhere (e.g., data attribute on the modal element)
    // const response = await fetch(interactionUrl);
    const csrftoken = getCookie('csrftoken');
    const scheduleUrl = `/shift_detail?shift_schedule_id=${shift_id}`;
        fetch(scheduleUrl, {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken
            }
        })
        .then(response => {
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            return response.json();
        })
        .then(data => {
          document.getElementById("id_edit_shift_date").value=data.shift_date
          document.getElementById("id_edit_assigned_staff_name").value=data.assigned_staff_name
          document.getElementById("id_edit_shift_type").value=data.shift_type
          document.getElementById("id_shift_id").value=data.shift_schedule_id

    })
          .catch(error => {
            console.error('Error:', error);
        });
    
  
};

function getCookie(name) {
          let cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              const cookies = document.cookie.split(';');
              for (let i = 0; i < cookies.length; i++) {
                  const cookie = cookies[i].trim();
                  // Check if the cookie name matches the desired name
                  if (cookie.startsWith(name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
        }
         
</script>
  <script src="{% static 'node_modules/preline/dist/preline.js' %}"></script>
</body>

</html>